"""Creacion inicial tablas MODD

Revision ID: 25b4a2a8460d
Revises: 
Create Date: 2026-06-17 19:43:46.751319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b4a2a8460d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requerimientos',
    sa.Column('id_requerimientos', sa.Integer(), nullable=False),
    sa.Column('acomodo', sa.String(), nullable=True),
    sa.Column('equipo_de_sonido', sa.Boolean(), nullable=True),
    sa.Column('cafeteria', sa.Boolean(), nullable=True),
    sa.Column('videoconferencia', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_requerimientos')
    )
    op.create_index(op.f('ix_requerimientos_id_requerimientos'), 'requerimientos', ['id_requerimientos'], unique=False)
    op.create_table('sala',
    sa.Column('numero_sala', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('numero_sala')
    )
    op.create_index(op.f('ix_sala_numero_sala'), 'sala', ['numero_sala'], unique=False)
    op.create_table('solicitante',
    sa.Column('id_solicitante', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('no_de_telefono', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_solicitante')
    )
    op.create_index(op.f('ix_solicitante_correo'), 'solicitante', ['correo'], unique=True)
    op.create_index(op.f('ix_solicitante_id_solicitante'), 'solicitante', ['id_solicitante'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('solicitud',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('hora_de_solicitud', sa.Time(), nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitante'], ['solicitante.id_solicitante'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_index(op.f('ix_solicitud_id_solicitud'), 'solicitud', ['id_solicitud'], unique=False)
    op.create_table('evento',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_de_inicio', sa.Time(), nullable=False),
    sa.Column('hora_de_termino', sa.Time(), nullable=False),
    sa.Column('no_de_asistentes', sa.Integer(), nullable=True),
    sa.Column('id_solicitud', sa.Integer(), nullable=True),
    sa.Column('id_requerimientos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_requerimientos'], ['requerimientos.id_requerimientos'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index(op.f('ix_evento_id_evento'), 'evento', ['id_evento'], unique=False)
    op.create_table('sala_evento',
    sa.Column('numero_sala', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id_evento'], ),
    sa.ForeignKeyConstraint(['numero_sala'], ['sala.numero_sala'], ),
    sa.PrimaryKeyConstraint('numero_sala', 'id_evento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sala_evento')
    op.drop_index(op.f('ix_evento_id_evento'), table_name='evento')
    op.drop_table('evento')
    op.drop_index(op.f('ix_solicitud_id_solicitud'), table_name='solicitud')
    op.drop_table('solicitud')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_solicitante_id_solicitante'), table_name='solicitante')
    op.drop_index(op.f('ix_solicitante_correo'), table_name='solicitante')
    op.drop_table('solicitante')
    op.drop_index(op.f('ix_sala_numero_sala'), table_name='sala')
    op.drop_table('sala')
    op.drop_index(op.f('ix_requerimientos_id_requerimientos'), table_name='requerimientos')
    op.drop_table('requerimientos')
    # ### end Alembic commands ###
