"""agregar columna estado a solicitud

Revision ID: d8e1c16088f4
Revises: 25b4a2a8460d
Create Date: 2026-06-18 01:35:16.813258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e1c16088f4'
down_revision: Union[str, None] = '25b4a2a8460d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('estado', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitud', 'estado')
    # ### end Alembic commands ###
